services:
  server:
    build: .
    restart: unless-stopped
    volumes:
      - config:/app/config

  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED}
    command: tunnel --no-autoupdate run
    network_mode: "service:server"

volumes:
  config:
