games:
  "yume":
    name: "Yume Nikki"
    permission: Yume1kki
  "2kki":
    name: "Yume 2kki"
    permission: Yume2kki
  "flow":
    name: ".flow"
  "unevendream":
    name: "Uneven Dream"
  "deepdreams":
    name: "Deep Dreams"
  "someday":
    name: "Someday"
  "amillusion":
    name: "Amillusion"
  "braingirl":
    name: "Braingirl"
  "muma":
    name: "Muma|Rope"
  "genie":
    name: "Dream Genie"
  "mikan":
    name: "Mikan Muzou"
  "ultraviolet":
    name: "Ultraviolet"
  "sheawaits":
    name: "She Awaits"
  "oversomnia":
    name: "Oversomnia"
  "tsushin":
    name: "Yume Tsushin"
  "nostalgic":
    name: "NostAlgic"
  "oneshot":
    name: "OneShot"
  "if":
    name: "If"
  "unaccomplished":
    name: "Unaccomplished"
  "fog":
    name: "FOG"
  "cold":
    name: "[COLD]"
  "loveyou":
    name: "loveyou"
  "okuri":
    name: "Okuri"
  "scarynikki":
    name: "Scary Nikki"
  "space":
    name: "Space Funeral"
  